

SCADA_INIT_METHODS = ["INITAUTOMAPSCADALINK",	"INITDASCADALINK",	"INITDFOSCADALINK",	"INITDFOSCADALINKBUS",	"INITDFOSCADALINKXFMR",	"INITDASCADALINKBKR",	"INITDASCADALINKBUS",	"INITDASCADALINKFDR",	"INITDASCADALINKMAIN",	"INITDASCADALINKXFMR"]


FIELD_INIT_METHODS = ["INITMMSCONTROLS",	"INIT",	"INITLOOP",	"INITBUS",	"INITBKR",	"INITBKRLOOP",	"INITFDR",	"INITMAIN",	"INITXFMR",	"INITFDRLOOP"]


FIELD_INIT_METHOD_INPUTS = ["PDEVICEOFFLINE ",	"PFIELDFIRST_AI",	"PFIELDFIRST_AO",	"PFIELDFIRST_BI",	"PFIELDFIRST_BO",	"PFIELDFIRST_BO_DPC",	"PFIELDFIRST_BO_SPC",	"PFIELDFIRST_CNT",	"PMESSAGERECEIVEDCOUNT ",	"PPOLL ",	"PPOUPOLLEVENTPERIOD ",	"PPOUPOLLINTEGRITYPERIOD "]